# Site settings
title: kylez.org
description: >
    Kyle's pages.
author: Kyle Zhao
email: keyu98@qq.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kylez.org" # the base hostname & protocol for your site
github_username:  keyu98
private_email: goldofzky@gmail.com
# disqus_shortname: YourDisqusShortname

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title
sass:
    style: compressed

gems:
  - jemoji
  - jekyll-sitemap
# - amp-jekyll # Acceletrated Mobile Pages

# AMP Settings
# ampdir: amp/
# enable_amp: true

# Google Analytics
# google_analytics: UA-XXXXXXXX-X
